/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define BTOR_CC "gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define BTOR_CFLAGS "-W -Wall -Wextra -O3 -DNDEBUG -DBTOR_USE_PICOSAT -DBTOR_USE_LINGELING -DBTOR_USE_MINISAT -I../minisat"
#define BTOR_OS "Linux chili7 3.2.0-32-generic x86_64"
#define BTOR_COMPILED "Sat Oct 13 13:42:34 CEST 2012"
#define BTOR_RELEASED "Sat Oct 13 13:42:34 CEST 2012"
#define BTOR_VERSION "1.5.118"
#define BTOR_ID "f55df7d23bd4f90841f92e4e30f558ad8fe92cb1"
